// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MYDBContext))]
    partial class MYDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.LJX.MenusModel", b =>
                {
                    b.Property<int>("Menus_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Menus_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Menus_ID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Models.LJX.RoleMenuModel", b =>
                {
                    b.Property<int>("RoleMenu_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleMenu_MenuID")
                        .HasColumnType("int");

                    b.Property<int>("RoleMenu_RolrID")
                        .HasColumnType("int");

                    b.HasKey("RoleMenu_ID");

                    b.ToTable("RoleMenu");
                });

            modelBuilder.Entity("Models.LJX.RoleModel", b =>
                {
                    b.Property<int>("Roles_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Roles_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Roles_ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Models.LJX.UserModel", b =>
                {
                    b.Property<int>("Users_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("User_Pwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Users_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Models.LJX.UserRoleModel", b =>
                {
                    b.Property<int>("UserRole_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserRole_RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserRole_UserID")
                        .HasColumnType("int");

                    b.HasKey("UserRole_ID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Models.WYH.YonghuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("dentification_card_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sex")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("yonghu");
                });

            modelBuilder.Entity("Models.WYH.landlordModel", b =>
                {
                    b.Property<int>("landlord_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("landlord_Age")
                        .HasColumnType("int");

                    b.Property<int>("landlord_HouseID")
                        .HasColumnType("int");

                    b.Property<string>("landlord_Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("landlord_Sex")
                        .HasColumnType("int");

                    b.Property<string>("landlord_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("landlord_poc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("landlord_ID");

                    b.ToTable("landlord");
                });

            modelBuilder.Entity("Models.YH.AreaModel", b =>
                {
                    b.Property<int>("qu_site_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("qu_site_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("qu_site_ID");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("Models.YH.City_Model", b =>
                {
                    b.Property<int>("shi_site_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("shi_site_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shi_site_ID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Models.YH.HouseModel", b =>
                {
                    b.Property<int>("house_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_lxname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("house_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("house_qu")
                        .HasColumnType("int");

                    b.Property<string>("house_rent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("house_sheng")
                        .HasColumnType("int");

                    b.Property<int>("house_shi")
                        .HasColumnType("int");

                    b.Property<int>("house_state")
                        .HasColumnType("int");

                    b.HasKey("house_id");

                    b.ToTable("House");
                });

            modelBuilder.Entity("Models.YH.provinceModel", b =>
                {
                    b.Property<int>("sheng_site_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sheng_site_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sheng_site_ID");

                    b.ToTable("province");
                });

            modelBuilder.Entity("Models.YYF.FinanceModel", b =>
                {
                    b.Property<int>("finance_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("finance_contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finance_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("finance_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("finance_yfmoney")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("finance_ysmoney")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("finance_ID");

                    b.ToTable("Finance");
                });
#pragma warning restore 612, 618
        }
    }
}
